---
title: "Plots for Midcourse Project"
output: html_document
date: "2023-01-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Add required Libraries
```{r cars}
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(treemapify)
library(grid)
```

#read in Rdata File "prices"
```{r}
prices <- readRDS("prices.RData")
```

#ggplot dynamic histogram of distribution of List Price frequencies within given Format, Category, and Page Count filters -- annotations dynamic within given xlim params
```{r}
format <- 'Trade Paperback'
level_1 <- 'SOCIAL SCIENCE'
pcb <- '251 - 300'
bins <- 50


p <- prices %>% 
  filter(Format == format & 
           BISAC_Level_1 == level_1 & 
           page_count_bucket == pcb)

median <- median(p$List_Price_Value, na.rm = TRUE) %>% 
  format(round(2), nsmall = 2)

median

price_plot <- p %>% 
    ggplot(aes(x = List_Price_Value)) + 
    geom_histogram(color = 1, fill = 'skyblue', bins = bins) + 
    geom_vline(xintercept = median(p$List_Price_Value, na.rm = TRUE), 
             linetype="dotted", 
             color = 'red',
             lwd = 1) +
    coord_cartesian(expand = TRUE, clip = 'off') +
    scale_x_continuous(breaks = seq(0,1000, by = 10))

xlim <- layer_scales(price_plot)$x$range$range
ylim <- layer_scales(price_plot)$y$range$range

price_plot + 
  annotate("text",
             x = xlim[2] /2 + 2,
             y = ylim[2] /2 + 5,
             label = paste("Median (---) = $", median),
             color = "red",
             size = 4) +
      labs(x = 'List Price ($)', y = 'Frequency') +
      labs(title = "2022 List Price Frequency Distribution") +
      labs(caption = "Data: limited to 2022 pub dates w/ >= 3 reported sales (Ingram Book Company)")
```
#Bar Plot to visualize share of Level 2 categorization within Level 1 by frequency

```{r}
p2 <- prices %>% 
  filter(Format == format & BISAC_Level_1 == level_1) %>%
    group_by(BISAC_Level_1, BISAC_Level_2) %>% 
    summarize(count = n()) %>% 
    arrange(desc(count))
  
p3 <- p2[1:10, ] 
  
p3 %>%   
  ggplot(aes(x = BISAC_Level_1, y = count, fill = BISAC_Level_2)) +
  geom_bar(stat = "identity") +
  labs(x = "BISAC Level 1", y = "Top 10 Frequency") +
  labs(title = "Top 10 BISAC Level 2 Categories by Title Count") +
  labs(caption = "Data: limited to 2022 pub dates w/ >= 3 reported sales (Ingram Book Company)") +
  labs(fill = "BISAC Level 2")
```

